version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - echo Build Started on `date`      
  build:
    commands:      
      - echo Compiling
  post_build:
    commands:
      - echo Build Completed on `date`      
artifacts:
  files:
    - "**/*"